config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/welcome' => 'sessions#new'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :servers, only: %i[index create update show] do
    resources :channels, only: %i[index create], controller: 'servers/channels'
    resources :periods, only: :index, controller: 'servers/periods'
    resources :members, only: :index, controller: 'servers/members'
  end

  resources :ranks, only: :index
end

app/views/layouts/_breadcrumb.html.slim
.container.mt-3
  ol.breadcrumb
    = render_breadcrumbs tag: 'li class="breadcrumb-item"', separator: ''

app/views/layouts/_flash.html.slim
.container.mt-3
  - if notice.present?
    .alert.alert-success.alert-dismissible role='alert'
      = notice
      button.btn-close data-bs-dismiss='alert' aria-label='Close'
  - if alert.present?
    .alert.alert-danger.alert-dismissible role='alert'
      = alert
      button.btn-close data-bs-dismiss='alert' aria-label='Close'

app/views/layouts/_menu.html.slim
nav.navbar.navbar-white.bg-white
  .container
    .navbar-brand
    .d-flex
      .dropdown
        button#dropdownMenu.rounded-pill.btn.btn-link.p-0.text-decoration-none data-bs-toggle='dropdown' aria-expanded='false'
          img.rounded-circle src=current_user.avatar_url alt=current_user.username_discriminator width=36
        ul.dropdown-menu.dropdown-menu-end.shadow aria-labelledby='dropdownMenu'
          li
            span.dropdown-item-text
              = current_user.username_discriminator
          li
            hr.dropdown-divider
          li
            = link_to '参加したサーバー', servers_path, class: 'dropdown-item'
          li
            = link_to 'ボットを招待', invite_bot_url, class: 'dropdown-item'
          li
            hr.dropdown-divider
          li
            = link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item text-danger'

app/views/layouts/_ogp.html.slim
meta property='og:title' content='Chatrank - Member ranking by message number DiscordBot'
meta property='og:type' content='website'
meta property='og:url' content=root_url
meta property='og:image' content=url_to_image('chatrank-ogp.png')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Chatrank | Member ranking by message number DiscordBot
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = render 'layouts/ogp'
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if current_user.present?
      = render 'layouts/menu'
    = render 'layouts/breadcrumb'
    = render 'layouts/flash'
    .container.my-3
      = yield